[package]
name = "piston-test"
version = "0.1.0"
authors = ["octalsrc <nicklewchenko92@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
piston = "0.46.0"
piston_window = "0.96.0"